# Generated by Django 4.2.4 on 2023-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupons',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de modificação'),
        ),
    ]
