# Generated by Django 4.2.4 on 2023-08-28 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('titulo', models.CharField(choices=[('EASY TO USED', 'Fácil para usar'), ('AWESOME DESIGN', 'Design'), ('EASY TO CUSTOMIZE', 'Facil para costumizar'), ('UI/UX DESIGN', 'UI e UX'), ('APP DEVELOPMENT', 'Desenvolvimento de app'), ('USER FRIENDLY INTERFACE', 'Interface fácil')], max_length=30, verbose_name='Título')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Grafíco'), ('lni-users', 'Usuário'), ('lni-layers', 'UI/UX'), ('lni-mobile', 'Celular'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('bio', models.CharField(max_length=200, verbose_name='Biografia')),
                ('imagem', models.ImageField(upload_to='equipe', verbose_name='Imagem')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Galera',
            },
        ),
    ]
